create extension if not exists pgcrypto;
create table public.profiles(id uuid primary key references auth.users(id) on delete cascade, email text not null, role text not null check(role in ('admin','observer')), created_at timestamptz not null default now());
create table public.constitutions(id uuid primary key default gen_random_uuid(),name text not null,version text not null unique,content text not null,sha256 text not null,active boolean not null default true,created_at timestamptz not null default now(),check(sha256=encode(sha256(convert_to(content,'UTF8')),'hex')));
create table public.experiments(id uuid primary key default gen_random_uuid(),name text not null,constitution_id uuid not null references public.constitutions(id),model text not null,status text not null default 'paused' check(status in ('paused','running','reflecting','day_complete','stopped')),day int not null default 1 check(day>0),action_budget int not null default 20 check(action_budget between 1 and 200),actions_used int not null default 0 check(actions_used>=0 and actions_used<=action_budget),skill_selections int not null default 0 check(skill_selections between 0 and 3),skill_costs_action boolean not null default false,active_skill_id uuid,location text not null default 'center',is_demo boolean not null default false,lease_token uuid,lease_until timestamptz,revision int not null default 0,last_error text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.experiment_members(experiment_id uuid not null references public.experiments(id),profile_id uuid not null references public.profiles(id) on delete cascade,primary key(experiment_id,profile_id));
create table public.cycles(id uuid primary key default gen_random_uuid(),experiment_id uuid not null references public.experiments(id),day int not null,action_number int not null,phase text not null check(phase in ('action','reflection')),status text not null default 'pending' check(status in ('pending','completed','failed','cancelled')),lease_token uuid not null,context jsonb,model text not null,constitution_id uuid not null references public.constitutions(id),error text,created_at timestamptz not null default now(),completed_at timestamptz);
create table public.actions(id uuid primary key default gen_random_uuid(),experiment_id uuid not null references public.experiments(id),cycle_id uuid not null unique references public.cycles(id),type text not null,target uuid,payload jsonb not null,result jsonb not null,cost int not null check(cost in (0,1)),created_at timestamptz not null default now());
create table public.observations(id uuid primary key default gen_random_uuid(),experiment_id uuid not null references public.experiments(id),cycle_id uuid references public.cycles(id),content text not null,object_id uuid,source text not null default 'environment',created_at timestamptz not null default now());
create table public.decision_records(id uuid primary key default gen_random_uuid(),experiment_id uuid not null references public.experiments(id),cycle_id uuid not null unique references public.cycles(id),record jsonb not null,created_at timestamptz not null default now());
create table public.memories(id uuid primary key default gen_random_uuid(),experiment_id uuid not null references public.experiments(id),type text not null check(type in ('episodic','knowledge','salient','self_model')),title text not null,content text not null,reason_saved text not null,importance float not null check(importance between 0 and 1),confidence float not null check(confidence between 0 and 1),cycle_created uuid references public.cycles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),last_recalled_at timestamptz,recall_count int not null default 0,archived boolean not null default false,search_vector tsvector generated always as (to_tsvector('english',title||' '||content)) stored);
create index memories_search on public.memories using gin(search_vector);
create table public.memory_retrievals(id uuid primary key default gen_random_uuid(),experiment_id uuid not null references public.experiments(id),cycle_id uuid not null references public.cycles(id),memory_id uuid not null references public.memories(id),score float not null,reasons jsonb not null,created_at timestamptz not null default now());
create table public.skills(id uuid primary key default gen_random_uuid(),slug text not null unique,name text not null,description text not null,when_useful text not null,instructions text not null,source text not null,source_sha256 text,enabled boolean not null default false,category text not null check(category in ('reasoning','exploration','reflection','memory','experimentation','planning','creativity')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.experiments add foreign key(active_skill_id) references public.skills(id);
create table public.skill_usage(id uuid primary key default gen_random_uuid(),experiment_id uuid not null references public.experiments(id),cycle_id uuid not null references public.cycles(id),skill_id uuid not null references public.skills(id),reason_summary text not null,result text,subsequent_action_id uuid references public.actions(id),duration_ms int,context jsonb,created_at timestamptz not null default now());
create table public.graph_nodes(id uuid primary key default gen_random_uuid(),experiment_id uuid not null references public.experiments(id),node_type text not null check(node_type in ('observation','memory','object','concept','hypothesis','question','discovery','skill','action','self_model')),reference_id uuid,label text not null,summary text not null,importance float not null check(importance between 0 and 1),confidence float not null check(confidence between 0 and 1),evidence_ids uuid[] not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(id,experiment_id),unique(experiment_id,node_type,reference_id));
create table public.graph_edges(id uuid primary key default gen_random_uuid(),experiment_id uuid not null references public.experiments(id),source_node_id uuid not null,target_node_id uuid not null,relationship text not null check(relationship in ('observed','related_to','caused','possibly_caused','contradicts','supports','located_near','learned_from','tested_with','resulted_in','reminds_of','used_skill','preference_for','revised_by','followed_by')),strength float not null check(strength between 0 and 1),confidence float not null check(confidence between 0 and 1),status text not null check(status in ('confirmed','tentative','contradicted','historical')),evidence_ids uuid[] not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),foreign key(source_node_id,experiment_id) references public.graph_nodes(id,experiment_id),foreign key(target_node_id,experiment_id) references public.graph_nodes(id,experiment_id),unique(experiment_id,source_node_id,target_node_id,relationship));
create table public.environment_objects(id uuid primary key default gen_random_uuid(),experiment_id uuid not null references public.experiments(id),name text not null,public_description text not null,internal_state jsonb not null default '{}',available_actions jsonb not null,hidden_properties jsonb not null default '{}',location text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.observations add foreign key(object_id) references public.environment_objects(id);
create table public.environment_events(id uuid primary key default gen_random_uuid(),experiment_id uuid not null references public.experiments(id),cycle_id uuid references public.cycles(id),event_type text not null,payload jsonb not null,created_at timestamptz not null default now());
create table public.journal_entries(id uuid primary key default gen_random_uuid(),experiment_id uuid not null references public.experiments(id),cycle_id uuid not null references public.cycles(id),content text not null,kind text not null,created_at timestamptz not null default now());
create table public.messages(id uuid primary key default gen_random_uuid(),experiment_id uuid not null references public.experiments(id),sender_id uuid references public.profiles(id),sender_type text not null check(sender_type in ('observer','seeded','system')),content text not null check(length(content) between 1 and 2000),cycle_id uuid references public.cycles(id),created_at timestamptz not null default now());
create table public.capabilities(id uuid primary key default gen_random_uuid(),experiment_id uuid not null references public.experiments(id),name text not null check(name in ('communication','skills','memory','graph')),enabled boolean not null default true,created_at timestamptz not null default now(),unique(experiment_id,name));
create table public.experiment_logs(id uuid primary key default gen_random_uuid(),experiment_id uuid not null references public.experiments(id),cycle_id uuid references public.cycles(id),event_type text not null,summary text not null,payload jsonb not null default '{}',created_at timestamptz not null default now());
create function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from profiles where id=auth.uid() and role='admin')$$;
create function public.can_view(e uuid) returns boolean language sql stable security definer set search_path=public as $$select public.is_admin() or exists(select 1 from experiment_members where experiment_id=e and profile_id=auth.uid())$$;
create function public.immutable_record() returns trigger language plpgsql as $$begin raise exception 'Record is append-only';end$$;
create trigger immutable_constitution before update or delete on public.constitutions for each row execute function public.immutable_record();
create trigger immutable_log before update or delete on public.experiment_logs for each row execute function public.immutable_record();
create trigger immutable_journal before update or delete on public.journal_entries for each row execute function public.immutable_record();
create trigger immutable_decision before update or delete on public.decision_records for each row execute function public.immutable_record();
create trigger immutable_observation before update or delete on public.observations for each row execute function public.immutable_record();
create trigger immutable_action before update or delete on public.actions for each row execute function public.immutable_record();
create function public.pin_constitution() returns trigger language plpgsql as $$begin if new.constitution_id<>old.constitution_id or new.model<>old.model or new.is_demo<>old.is_demo then raise exception 'Experiment identity is immutable';end if;return new;end$$;
create trigger pinned_experiment before update on public.experiments for each row execute function public.pin_constitution();
-- Default-deny writes, including profiles. No public signup trigger or role metadata trust.
alter table public.profiles enable row level security;
create policy profile_read on public.profiles for select to authenticated using(id=auth.uid() or public.is_admin());
alter table public.experiment_members enable row level security;
create policy membership_read on public.experiment_members for select to authenticated using(profile_id=auth.uid() or public.is_admin());
alter table public.constitutions enable row level security;
create policy constitution_read on public.constitutions for select to authenticated using(exists(select 1 from public.profiles where id=auth.uid()));
alter table public.skills enable row level security;
create policy skills_read on public.skills for select to authenticated using(exists(select 1 from public.profiles where id=auth.uid()));
-- Detailed skill instructions are server-only even to authenticated observers.
revoke all on public.skills from anon,authenticated;
grant select(id,slug,name,description,when_useful,source,source_sha256,enabled,category,created_at,updated_at) on public.skills to authenticated;
alter table public.experiments enable row level security;
create policy experiment_read on public.experiments for select to authenticated using(public.can_view(id));
alter table public.environment_objects enable row level security;
-- No read policy on hidden environmental truth. Only safe projections leave the backend.
do $$declare t text;begin foreach t in array array['cycles','actions','observations','decision_records','memories','memory_retrievals','skill_usage','graph_nodes','graph_edges','environment_events','journal_entries','messages','capabilities','experiment_logs'] loop
 execute format('alter table public.%I enable row level security',t);
 execute format('create policy member_read on public.%I for select to authenticated using(public.can_view(experiment_id))',t);
 execute format('create index on public.%I(experiment_id,created_at desc)',t);
end loop;end$$;
create index on public.environment_objects(experiment_id);
create index on public.cycles(experiment_id,status);
create index on public.experiments(status,lease_until);
-- Postgres Changes only publishes observer-safe tables; private environment truth is excluded.
do $$declare t text;begin foreach t in array array['experiments','actions','observations','decision_records','memories','skill_usage','graph_nodes','graph_edges','journal_entries','messages','capabilities','experiment_logs'] loop
 execute format('alter publication supabase_realtime add table public.%I',t);
end loop;end$$;
